### ISSUE TITLE
ISubdSchema: ERROR EXCEPTION: Can't obtain dimension info for sample with index:1 (kid:0)

### ISSUE THREAD

**Issue by zhoub** [j-cube/multiverse#1]
ERROR EXCEPTION: Can't obtain dimension info for sample with index:1 (kid:0)

Reproduceable from the unit test AbcGeom_SubDTest.

**Comment by pberto** [comment]
@panta note that this was working in the private repository we were using before, so maybe we forgot to cherry pick everything, better double check.

**Comment by panta** [comment]
Hey guys, I've tried in a gazillion ways to replicate this, without effect, both on linux and OSX.
Can you point me to the exact commit (and platform, etc.) you are using?

**Comment by pberto** [comment]
It's more easy to catch this on windows, @zhoub sent you a small repro for Linux.

**Comment by panta** [comment]
Fixed (hopefully) in 31cbc4d.
