### ISSUE TITLE
Unqlite: The Performance

### ISSUE THREAD

**Issue by zhoub** [j-cube/multiverse#11]
```
Lacrimosa:multiverse-clang6 Bo$ time abcconvert -toGit ZombieJump.abc /tmp/ZombieJump-native.git

real    0m12.948s
user    0m7.923s
sys 0m4.116s

Lacrimosa:multiverse-redis Bo$ time abcconvert -toGit ZombieJump.abc /tmp/ZombieJump-unqlite.git

real    0m4.067s
user    0m3.323s
sys 0m0.560s
```

You can see how fast the unqlite backend on my MAC wih SSD. I think to local application this is one of the candidate solution for libgit2. We don't need the extra overhead on SQL statement such as SQLITE. User also doesn't want to start an instance of redis server at background just only to read/write cache. What we need is just a KV database, that's all.

**Comment by pberto** [comment]
Fantastic @zhoub - Let's bring this into the main line ASAP. @panta we'll get this done on our side, let's discuss privately about the other improvements we were planning. I foresee a huge performance improvements between the two :+1:

**Comment by pberto** [comment]
@zhoub nice hostname :)

**Comment by zhoub** [comment]
I will refactor the current several test backends in our codebase to make this more generic. Now I just keep the **redis** and **unqlite** as built-in backends, going to remove the **sqlite** and **memcached**. @panta Hey Marco what do you think ?

**Comment by zhoub** [comment]
I need a bit more time to explore the different configuration in unqlite. Found some issues.

**Comment by pberto** [comment]
This can be closed since we are moving along with the other plan ;-)
