### ISSUE TITLE
"archive.json" ---> "archive.json.abc"

### ISSUE THREAD

**Issue by pberto** [j-cube/multiverse#3]
Some applications (e.g. Maya) cannot open an alembic directory (in multiverse an alembic asset is a repository enclosed in a directory) therefore we currently use a placeholder file inside the alembic directory/repository called `archive.json`. We need to change naming of this file to `archive.json.abc` because of convenience fo registering file formats for multiverse in the DCC we are supporting (and about to support)

**Comment by panta** [comment]
Fixed in 07dad18.
