### ISSUE TITLE
Merge latest Alembic in master

### ISSUE THREAD

**Issue by zhoub** [j-cube/multiverse#6]
Since recently Alembic is able to be compiled as a shared library and they also changed the makefile a lot, @panta please consider this, thanks!

**Comment by pberto** [comment]
Actually this is necessary since in multiverse for Houdini, which is derived from the SESI code, they link dynamically too.

**Comment by zhoub** [comment]
Hi Macro,

Now we need this for the latest Maya 2016.5 plugin, now on Mac it switched to the C++11 with libcpp, so the old routines to pick which header to include become annoying. Please have a look at this, ciao.

**Comment by panta** [comment]
Merged upstream 1.7.0 into [panta/alembic-1.7.0-port](https://github.com/j-cube/multiverse/tree/panta/alembic-1.7.0-port).
