### ISSUE TITLE
Start a branch with libgit2 v0.23.3

### ISSUE THREAD

**Issue by pberto** [j-cube/multiverse#8]
https://github.com/libgit2/libgit2/releases

**Comment by pberto** [comment]
@panta note that there is a API change in .23:

https://libgit2.github.com/libgit2/#v0.23.0/group/branch/git_branch_create

**Comment by panta** [comment]
Created the branch [1.5.8/multiverse-libgit-0.23](https://github.com/j-cube/multiverse/tree/1.5.8/multiverse-libgit-0.23).
Just to test, I've also created a corresponding branch for alembic-builder (for OSX): [osx-multiverse-1.5.8-libgit-0.23](https://github.com/j-cube/alembic-builder/tree/osx-multiverse-1.5.8-libgit-0.23).

Can be closed I think.
